<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import { v4 as uuidv4 } from "uuid";
  import type { Template } from "../types/Template";
  import { removeEntryWithId } from "../../../lib/utilities/array";

  export let template: Template;

  const dispatch = createEventDispatcher();

  function handleSubmit() {
    if (template.instructions == undefined) template.instructions = "";

    dispatch("submit", template);
  }

  // add a new item to the template
  function addItem() {
    // create an empty array if it doesn't exist
    if (!template.items) {
      template.items = [];
    }

    template.items.push({
      // create a temporary id for new entries. The real id is generated by the server when the dataset gets saved.
      id: uuidv4(),
      name: "",
      qualifier: "",
    });
  }

  const deleteTemplateItem = (templateItemId: string) => {
    template.items = removeEntryWithId(template.items, templateItemId);
  };

  let formData = {
    name: "",
    instructions: "",
  };
</script>

<form on:submit|preventDefault={handleSubmit}>
  <div class="text-lg text-center">
    <input type="text" class="text-center bg-slate-100" bind:value={template.name} />
  </div>

  <div class="text-xl text-center mt-10">Zutaten</div>
  <div class="border">
    <div class="grid grid-cols-3 mt-4 text-center">
      <div class="border-b">Zutat</div>
      <div class="border-b">Menge</div>
      <div class="border-b"></div>
      <div class="col-span-3 mb-4" />
      {#if !!template.items}
        {#each template.items as item (item.id)}
          <div title={item.id} class="">
            <input type="text" class="text-center w-full bg-slate-100" bind:value={item.name} />
          </div>
          <div>
            <input type="text" class="text-center w-full bg-slate-100" bind:value={item.qualifier} />
          </div>
          <div>
            <button on:click={() => deleteTemplateItem(item.id)} class="border boder-black px-2 text-lg bg-slate-700 text-white text-center">X</button>
          </div>
        {/each}
      {/if}
    </div>
    <button
      class="border boder-black px-2 text-lg bg-slate-700 mt-2 text-white text-center w-full"
      type="button"
      on:click={() => {
        addItem();
        // assign the same object to trigger a re-render
        template = { ...template };
      }}
    >
      Zutat hinzufügen
    </button>
  </div>

  <div class="text-xl text-center mt-10 mb-4">Beschreibung</div>
  <div>
    <textarea
      class="bg-slate-200 w-full p-2"
      bind:value={template.instructions}
      rows="10"
    />
  </div>

  <button
    type="submit"
    class="border boder-black px-2 text-lg bg-slate-700 mt-2 text-white text-center w-full"
    >Speichern</button
  >
</form>
