<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import { v4 as uuidv4 } from "uuid";
  import type { Template } from "./Template";
  import { removeEntryWithId } from "../../utilities/array";

  export let template: Template;

  const dispatch = createEventDispatcher();

  function handleSubmit() {

    if (template.instructions == undefined)
      template.instructions = '';

    dispatch("submit", template);
  }

  // add a new item to the template
  function addItem() {
    // create an empty array if it doesn't exist
    if (!template.items) {
      template.items = [];
    }

    template.items.push({
      // create a temporary id for new entries. The real id is generated by the server when the dataset gets saved.
      id: uuidv4(),
      name: "",
      amount: "",
    });
  }

  const deleteTemplateItem = (templateItemId: string) => {
    template.items = removeEntryWithId(template.items, templateItemId);
  };

  let formData = {
    name: "",
    instructions: "",
  };
</script>

<form on:submit|preventDefault={handleSubmit}>
  <label>
    <div>
      Name:
      <input type="text" bind:value={template.name} />
    </div>
  </label>
  <label>
    <div>
      Zutaten:
      {#if !!template.items}
        {#each template.items as item (item.id)}
          <div title={item.id}>
            <label>Name</label>
            <input type="text" bind:value={item.name} />
            <label>Menge</label>
            <input type="text" bind:value={item.amount} />
            <button on:click={() => deleteTemplateItem(item.id)}>X</button>
          </div>
        {/each}
      {/if}
      <button
        type="button"
        on:click={() => {
          addItem();
          // assign the same object to trigger a re-render
          template = { ...template };
        }}
      >
        Zutat hinzufügen
      </button>
    </div>
  </label>
  <label>
    <div>
      Schritte:
      <textarea bind:value={template.instructions} rows="20" />
    </div>
  </label>

  <button type="submit">Submit</button>
</form>
