name: Containerize ASP.NET Core application

on:
  push:
    branches: [ main ]
  # trigger manually
  workflow_dispatch:

env:
  PROJECT_NAME: meal-mate
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: "Say Hello to the commit id"
        run: echo "Hello, $GITHUB_SHA, or $(git rev-parse --short "$GITHUB_SHA")"
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Run unit tests
        run: dotnet test

      # Package the app into a linux-x64 container based on the dotnet/aspnet image
      # The properties of the image are managed in the .csproj file
      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer
      
      
      - name: Login to repository
        uses: actions-hub/docker/login@master
        env:
          DOCKER_REGISTRY_URL: registry.hub.docker.com
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Change tag of image to able to push it to the correct target and use a specific version tag
      - name: Tag built container
        uses: actions-hub/docker/cli@master
        with:
          args: tag api:1.0.0 registry.hub.docker.com/velox1992/meal-mate:${{ github.sha }}
          
      - name: Push built image to the registry
        uses: actions-hub/docker/cli@master
        with:
          args: push registry.hub.docker.com/velox1992/meal-mate:${{ github.sha }}
          
      # Change tag of image to able to push it to the correct target and use the latest tag
      - name: Tag built container
        uses: actions-hub/docker/cli@master
        with:
          args: api:1.0.0 registry.hub.docker.com/velox1992/meal-mate:latest

      - name: Push built image to the registry
        uses: actions-hub/docker/cli@master
        with:
          args: push registry.hub.docker.com/velox1992/meal-mate:latest
